### ISSUE TITLE
Can't load plugin

### ISSUE THREAD

**Issue by bonnedav** [ironboundred/AdvancedBan#7]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 3.0.11
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single
 
_What server version (/version) are you using?_
This server is running Paper version git-Paper-637 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
0

_Error_
[02:17:43] [Server thread/ERROR]: Could not load 'plugins/AdvancedBan-Bukkit-3.0.11-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.14
	at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[patched_1.13.2.jar:git-Paper-637]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-637]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-637]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-637]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-637]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by ironboundred** [comment]
It's trying to use the 1.14 api as I was using that to test and never changed it back so it would work on lower versions. Your servers using 1.13.2 which is what caused the error.

**Comment by bonnedav** [comment]
Ah makes sense. Just make it work on both if you can.
________________________________

**Comment by ironboundred** [comment]
newest release should work on 1.12 and newer now
